import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { IResProperties, ResProperties } from '../res-properties.model';
import { ResPropertiesService } from '../service/res-properties.service';

@Component({
  selector: 'jhi-res-properties-update',
  templateUrl: './res-properties-update.component.html',
})
export class ResPropertiesUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [null, [Validators.required]],
    communityId: [null, [Validators.required]],
    communityName: [null, [Validators.required, Validators.maxLength(255)]],
    builderId: [null, [Validators.required]],
    specialOffers: [null, [Validators.required, Validators.maxLength(255)]],
    brochure: [null, [Validators.required, Validators.maxLength(255)]],
    floorPlanId: [null, [Validators.required]],
    latitude: [null, [Validators.maxLength(20)]],
    longitude: [null, [Validators.maxLength(20)]],
    county: [null, [Validators.maxLength(32)]],
    heatsystem: [null, [Validators.maxLength(255)]],
    liststatus: [null, [Validators.maxLength(50)]],
    liststatusflag: [null, [Validators.maxLength(100)]],
    carportcap: [null, [Validators.maxLength(100)]],
    possession: [null, [Validators.maxLength(255)]],
    schoolname1: [null, [Validators.maxLength(32)]],
    subdivide: [null, [Validators.maxLength(50)]],
    vowavmyn: [null, [Validators.maxLength(1)]],
    presentuse: [null, [Validators.maxLength(255)]],
    proposeduse: [null, [Validators.maxLength(255)]],
    ranchname: [null, [Validators.maxLength(15)]],
    roombed2width: [],
    roomdininglevel: [null, [Validators.maxLength(50)]],
    roomliving2width: [],
    roomstudylevel: [null, [Validators.maxLength(50)]],
    area: [],
    areatitle: [null, [Validators.maxLength(255)]],
    assocfee: [],
    financeproposed: [null, [Validators.maxLength(255)]],
    listpriceorig: [],
    mapcoord: [null, [Validators.maxLength(5)]],
    schoolname2: [null, [Validators.maxLength(32)]],
    roomgaragewidth: [],
    roomkitchendesc: [null, [Validators.maxLength(255)]],
    roomliving1width: [],
    roomother2width: [],
    sqfttotal: [],
    officelistOfficenam1: [null, [Validators.maxLength(100)]],
    schoolname3: [null, [Validators.maxLength(32)]],
    zipcode: [null, [Validators.maxLength(25)]],
    barn1length: [],
    barn3width: [],
    roombed2length: [],
    roombed3length: [],
    roomother1width: [],
    agentlistFullname: [null, [Validators.maxLength(150)]],
    proptype: [null, [Validators.maxLength(50)]],
    mlsProptype: [null, [Validators.required, Validators.maxLength(50)]],
    schoolname4: [null, [Validators.maxLength(32)]],
    acrescultivated: [],
    barn2length: [],
    barn2width: [],
    complexname: [null, [Validators.maxLength(25)]],
    roombed4length: [],
    roombedbathdesc: [null, [Validators.maxLength(255)]],
    roombreakfastwidth: [],
    roomother: [null, [Validators.maxLength(255)]],
    roomutilitylength: [],
    acres: [],
    block: [null, [Validators.maxLength(7)]],
    directions: [null, [Validators.maxLength(150)]],
    subdivision: [null, [Validators.maxLength(40)]],
    yearbuilt: [],
    yearbuiltdetails: [null, [Validators.required, Validators.maxLength(255)]],
    agexemption: [null, [Validators.maxLength(1)]],
    barn1width: [],
    barn3length: [],
    roomdiningwidth: [],
    roomstudywidth: [],
    soiltype: [null, [Validators.maxLength(255)]],
    appraisername: [null, [Validators.maxLength(50)]],
    listpricelow: [],
    mappage: [null, [Validators.maxLength(5)]],
    unitnumber: [null, [Validators.required, Validators.maxLength(20)]],
    streetdir: [null, [Validators.maxLength(50)]],
    streettype: [null, [Validators.maxLength(50)]],
    subarea: [null, [Validators.maxLength(50)]],
    subareatitle: [null, [Validators.maxLength(255)]],
    bathshalf: [],
    roomgaragelength: [],
    propsubtype: [null, [Validators.maxLength(50)]],
    beds: [],
    roommasterbedwidth: [],
    roomstudylength: [],
    agentlist: [null, [Validators.maxLength(20)]],
    streetname: [null, [Validators.maxLength(50)]],
    roombreakfastlength: [],
    roomkitchenwidth: [],
    fence: [null, [Validators.maxLength(255)]],
    bathstotal: [],
    garagecap: [],
    sqftprice: [],
    style: [null, [Validators.maxLength(255)]],
    exterior: [null, [Validators.maxLength(255)]],
    foundation: [null, [Validators.maxLength(255)]],
    interior: [null, [Validators.maxLength(255)]],
    poolyn: [null, [Validators.maxLength(255)]],
    poolFeature: [null, [Validators.required, Validators.maxLength(255)]],
    listprice: [],
    listpricerange: [null, [Validators.maxLength(1)]],
    mlsnum: [null, [Validators.required, Validators.maxLength(50)]],
    matrixid: [null, [Validators.required]],
    remarks: [null, [Validators.maxLength(255)]],
    state: [null, [Validators.maxLength(50)]],
    roof: [null, [Validators.maxLength(255)]],
    securityfeatures: [null, [Validators.required, Validators.maxLength(255)]],
    utilitiesother: [null, [Validators.required, Validators.maxLength(255)]],
    commonfeatures: [null, [Validators.maxLength(255)]],
    construction: [null, [Validators.maxLength(255)]],
    modified: [null, [Validators.required]],
    stories: [],
    roomdininglength: [],
    roomliving1length: [],
    openhousetime: [null, [Validators.maxLength(25)]],
    openhouseendtime: [null, [Validators.required, Validators.maxLength(25)]],
    roomliving2length: [],
    lotdesc: [null, [Validators.maxLength(255)]],
    openhousedate: [],
    roommasterbedlength: [],
    roomother1length: [],
    officesellOfficenam2: [null, [Validators.maxLength(100)]],
    lotsize: [null, [Validators.maxLength(50)]],
    streetdirsuffix: [null, [Validators.maxLength(50)]],
    photocount: [],
    schooldistrict: [null, [Validators.maxLength(32)]],
    streetnum: [],
    utilities: [null, [Validators.maxLength(255)]],
    equipment: [null, [Validators.maxLength(255)]],
    roombed4width: [],
    roomkitchenlength: [],
    city: [null, [Validators.maxLength(32)]],
    garagedesc: [null, [Validators.maxLength(255)]],
    bathsfull: [],
    roombed3width: [],
    roomutildesc: [null, [Validators.maxLength(255)]],
    roomutilitywidth: [],
    roomfullbathlength: [null, [Validators.required, Validators.maxLength(10)]],
    roomfullbathwidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomhalfbathlength: [null, [Validators.required, Validators.maxLength(10)]],
    roomhalfbathwidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomexerciselength: [null, [Validators.required, Validators.maxLength(10)]],
    roomexercisewidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomstoragelength: [null, [Validators.required, Validators.maxLength(10)]],
    roomstoragewidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomgamelength: [null, [Validators.required, Validators.maxLength(10)]],
    roomgamewidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomguestlength: [null, [Validators.required, Validators.maxLength(10)]],
    roomguestwidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomlibrarylength: [null, [Validators.required, Validators.maxLength(10)]],
    roomlibrarywidth: [null, [Validators.required, Validators.maxLength(10)]],
    roommedialength: [null, [Validators.required, Validators.maxLength(10)]],
    roommediawidth: [null, [Validators.required, Validators.maxLength(10)]],
    roommudlength: [null, [Validators.required, Validators.maxLength(10)]],
    roommudwidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomofficelength: [null, [Validators.required, Validators.maxLength(10)]],
    roomofficewidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomsaunalength: [null, [Validators.required, Validators.maxLength(10)]],
    roomsaunawidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomsecondmasterlength: [null, [Validators.required, Validators.maxLength(10)]],
    roomsecondmasterwidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomsunlength: [null, [Validators.required, Validators.maxLength(10)]],
    roomsunwidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomspalength: [null, [Validators.required, Validators.maxLength(10)]],
    roomspawidth: [null, [Validators.required, Validators.maxLength(10)]],
    roomwinelength: [null, [Validators.required, Validators.maxLength(10)]],
    roomwinewidth: [null, [Validators.required, Validators.maxLength(10)]],
    juniorhighschoolname: [null, [Validators.required, Validators.maxLength(255)]],
    primaryschoolname: [null, [Validators.required, Validators.maxLength(255)]],
    seniorhighschoolname: [null, [Validators.required, Validators.maxLength(255)]],
    associationfee: [null, [Validators.required, Validators.maxLength(255)]],
    associationfeefrequency: [null, [Validators.required, Validators.maxLength(255)]],
    constructionmaterials: [null, [Validators.required, Validators.maxLength(255)]],
    heating: [null, [Validators.required, Validators.maxLength(255)]],
    accessoryunittype: [null, [Validators.required, Validators.maxLength(255)]],
    accessoryunityn: [null, [Validators.required, Validators.maxLength(255)]],
    flooring: [null, [Validators.required, Validators.maxLength(255)]],
    fireplacestotal: [null, [Validators.required, Validators.maxLength(255)]],
    fireplacefeatures: [null, [Validators.required, Validators.maxLength(255)]],
    securitysystemyn: [null, [Validators.required, Validators.maxLength(255)]],
    greenbuildingcertification: [null, [Validators.required, Validators.maxLength(255)]],
    greenenergyefficient: [null, [Validators.required, Validators.maxLength(255)]],
    energysavingfeatures: [null, [Validators.required, Validators.maxLength(255)]],
    lotnumber: [null, [Validators.required, Validators.maxLength(255)]],
    lotsizearea: [null, [Validators.required, Validators.maxLength(255)]],
    lotsizedimensions: [null, [Validators.required, Validators.maxLength(255)]],
    easements: [null, [Validators.required, Validators.maxLength(255)]],
    restrictions: [null, [Validators.required, Validators.maxLength(255)]],
    washerdryerconnections: [null, [Validators.required, Validators.maxLength(255)]],
    municipalutilitydistrictyn: [null, [Validators.required, Validators.maxLength(255)]],
    associationfeeincludes: [null, [Validators.required, Validators.maxLength(255)]],
    associationtype: [null, [Validators.required, Validators.maxLength(255)]],
    barninformation: [null, [Validators.required, Validators.maxLength(255)]],
    constructionmaterialswalls: [null, [Validators.required, Validators.maxLength(255)]],
    countyorparish: [null, [Validators.required, Validators.maxLength(255)]],
    exteriorbuildings: [null, [Validators.required, Validators.maxLength(255)]],
    farmranchfeatures: [null, [Validators.required, Validators.maxLength(255)]],
    fencedyardyn: [null, [Validators.required, Validators.maxLength(255)]],
    financingproposed: [null, [Validators.required, Validators.maxLength(255)]],
    handicapyn: [null, [Validators.required, Validators.maxLength(255)]],
    numberoftanksandponds: [null, [Validators.required, Validators.maxLength(255)]],
    parcelnumber: [null, [Validators.required, Validators.maxLength(255)]],
    virtualtoururlunbranded: [null, [Validators.required, Validators.maxLength(255)]],
    livingRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    masterBedRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    bedRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    diningRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    kitchenRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    breakfastRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    studyRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    utilityRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    fullBathRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    halfBathRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    exerciseRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    extraStorageRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    gameRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    guestRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    libraryRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    mediaRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    mudRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    officeRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    saunaRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    secondMasterRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    sunroomRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    spaRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    wineRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    otherRoomFeature: [null, [Validators.required, Validators.maxLength(255)]],
    isLuxury: [null, [Validators.required, Validators.maxLength(5)]],
    isMoveInReady: [null, [Validators.required, Validators.maxLength(5)]],
    photoUrl: [null, [Validators.maxLength(255)]],
    photo1Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo2Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo3Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo4Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo5Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo6Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo7Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo8Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo9Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo10Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo11Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo12Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo13Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo14Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo15Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo16Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo17Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo18Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo19Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo20Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo21Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo22Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo23Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo24Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo25Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo26Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo27Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo28Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo29Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo30Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo31Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo32Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo33Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo34Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo35Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo36Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo37Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo38Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo39Url: [null, [Validators.required, Validators.maxLength(255)]],
    photo40Url: [null, [Validators.required, Validators.maxLength(255)]],
    created: [],
    updated: [null, [Validators.required]],
    modifiedDate: [null, [Validators.required]],
    imgDeleted: [null, [Validators.required]],
    retsServer: [null, [Validators.maxLength(100)]],
    permalink: [null, [Validators.required, Validators.maxLength(255)]],
    propertyTag: [null, [Validators.required, Validators.maxLength(50)]],
    buildentoryViews: [null, [Validators.required]],
    location: [null, [Validators.required, Validators.maxLength(1000)]],
  });

  constructor(protected resPropertiesService: ResPropertiesService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ resProperties }) => {
      if (resProperties.id === undefined) {
        const today = dayjs().startOf('day');
        resProperties.modified = today;
        resProperties.openhousedate = today;
        resProperties.created = today;
        resProperties.updated = today;
        resProperties.modifiedDate = today;
      }

      this.updateForm(resProperties);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const resProperties = this.createFromForm();
    if (resProperties.id !== undefined) {
      this.subscribeToSaveResponse(this.resPropertiesService.update(resProperties));
    } else {
      this.subscribeToSaveResponse(this.resPropertiesService.create(resProperties));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IResProperties>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(resProperties: IResProperties): void {
    this.editForm.patchValue({
      id: resProperties.id,
      communityId: resProperties.communityId,
      communityName: resProperties.communityName,
      builderId: resProperties.builderId,
      specialOffers: resProperties.specialOffers,
      brochure: resProperties.brochure,
      floorPlanId: resProperties.floorPlanId,
      latitude: resProperties.latitude,
      longitude: resProperties.longitude,
      county: resProperties.county,
      heatsystem: resProperties.heatsystem,
      liststatus: resProperties.liststatus,
      liststatusflag: resProperties.liststatusflag,
      carportcap: resProperties.carportcap,
      possession: resProperties.possession,
      schoolname1: resProperties.schoolname1,
      subdivide: resProperties.subdivide,
      vowavmyn: resProperties.vowavmyn,
      presentuse: resProperties.presentuse,
      proposeduse: resProperties.proposeduse,
      ranchname: resProperties.ranchname,
      roombed2width: resProperties.roombed2width,
      roomdininglevel: resProperties.roomdininglevel,
      roomliving2width: resProperties.roomliving2width,
      roomstudylevel: resProperties.roomstudylevel,
      area: resProperties.area,
      areatitle: resProperties.areatitle,
      assocfee: resProperties.assocfee,
      financeproposed: resProperties.financeproposed,
      listpriceorig: resProperties.listpriceorig,
      mapcoord: resProperties.mapcoord,
      schoolname2: resProperties.schoolname2,
      roomgaragewidth: resProperties.roomgaragewidth,
      roomkitchendesc: resProperties.roomkitchendesc,
      roomliving1width: resProperties.roomliving1width,
      roomother2width: resProperties.roomother2width,
      sqfttotal: resProperties.sqfttotal,
      officelistOfficenam1: resProperties.officelistOfficenam1,
      schoolname3: resProperties.schoolname3,
      zipcode: resProperties.zipcode,
      barn1length: resProperties.barn1length,
      barn3width: resProperties.barn3width,
      roombed2length: resProperties.roombed2length,
      roombed3length: resProperties.roombed3length,
      roomother1width: resProperties.roomother1width,
      agentlistFullname: resProperties.agentlistFullname,
      proptype: resProperties.proptype,
      mlsProptype: resProperties.mlsProptype,
      schoolname4: resProperties.schoolname4,
      acrescultivated: resProperties.acrescultivated,
      barn2length: resProperties.barn2length,
      barn2width: resProperties.barn2width,
      complexname: resProperties.complexname,
      roombed4length: resProperties.roombed4length,
      roombedbathdesc: resProperties.roombedbathdesc,
      roombreakfastwidth: resProperties.roombreakfastwidth,
      roomother: resProperties.roomother,
      roomutilitylength: resProperties.roomutilitylength,
      acres: resProperties.acres,
      block: resProperties.block,
      directions: resProperties.directions,
      subdivision: resProperties.subdivision,
      yearbuilt: resProperties.yearbuilt,
      yearbuiltdetails: resProperties.yearbuiltdetails,
      agexemption: resProperties.agexemption,
      barn1width: resProperties.barn1width,
      barn3length: resProperties.barn3length,
      roomdiningwidth: resProperties.roomdiningwidth,
      roomstudywidth: resProperties.roomstudywidth,
      soiltype: resProperties.soiltype,
      appraisername: resProperties.appraisername,
      listpricelow: resProperties.listpricelow,
      mappage: resProperties.mappage,
      unitnumber: resProperties.unitnumber,
      streetdir: resProperties.streetdir,
      streettype: resProperties.streettype,
      subarea: resProperties.subarea,
      subareatitle: resProperties.subareatitle,
      bathshalf: resProperties.bathshalf,
      roomgaragelength: resProperties.roomgaragelength,
      propsubtype: resProperties.propsubtype,
      beds: resProperties.beds,
      roommasterbedwidth: resProperties.roommasterbedwidth,
      roomstudylength: resProperties.roomstudylength,
      agentlist: resProperties.agentlist,
      streetname: resProperties.streetname,
      roombreakfastlength: resProperties.roombreakfastlength,
      roomkitchenwidth: resProperties.roomkitchenwidth,
      fence: resProperties.fence,
      bathstotal: resProperties.bathstotal,
      garagecap: resProperties.garagecap,
      sqftprice: resProperties.sqftprice,
      style: resProperties.style,
      exterior: resProperties.exterior,
      foundation: resProperties.foundation,
      interior: resProperties.interior,
      poolyn: resProperties.poolyn,
      poolFeature: resProperties.poolFeature,
      listprice: resProperties.listprice,
      listpricerange: resProperties.listpricerange,
      mlsnum: resProperties.mlsnum,
      matrixid: resProperties.matrixid,
      remarks: resProperties.remarks,
      state: resProperties.state,
      roof: resProperties.roof,
      securityfeatures: resProperties.securityfeatures,
      utilitiesother: resProperties.utilitiesother,
      commonfeatures: resProperties.commonfeatures,
      construction: resProperties.construction,
      modified: resProperties.modified ? resProperties.modified.format(DATE_TIME_FORMAT) : null,
      stories: resProperties.stories,
      roomdininglength: resProperties.roomdininglength,
      roomliving1length: resProperties.roomliving1length,
      openhousetime: resProperties.openhousetime,
      openhouseendtime: resProperties.openhouseendtime,
      roomliving2length: resProperties.roomliving2length,
      lotdesc: resProperties.lotdesc,
      openhousedate: resProperties.openhousedate ? resProperties.openhousedate.format(DATE_TIME_FORMAT) : null,
      roommasterbedlength: resProperties.roommasterbedlength,
      roomother1length: resProperties.roomother1length,
      officesellOfficenam2: resProperties.officesellOfficenam2,
      lotsize: resProperties.lotsize,
      streetdirsuffix: resProperties.streetdirsuffix,
      photocount: resProperties.photocount,
      schooldistrict: resProperties.schooldistrict,
      streetnum: resProperties.streetnum,
      utilities: resProperties.utilities,
      equipment: resProperties.equipment,
      roombed4width: resProperties.roombed4width,
      roomkitchenlength: resProperties.roomkitchenlength,
      city: resProperties.city,
      garagedesc: resProperties.garagedesc,
      bathsfull: resProperties.bathsfull,
      roombed3width: resProperties.roombed3width,
      roomutildesc: resProperties.roomutildesc,
      roomutilitywidth: resProperties.roomutilitywidth,
      roomfullbathlength: resProperties.roomfullbathlength,
      roomfullbathwidth: resProperties.roomfullbathwidth,
      roomhalfbathlength: resProperties.roomhalfbathlength,
      roomhalfbathwidth: resProperties.roomhalfbathwidth,
      roomexerciselength: resProperties.roomexerciselength,
      roomexercisewidth: resProperties.roomexercisewidth,
      roomstoragelength: resProperties.roomstoragelength,
      roomstoragewidth: resProperties.roomstoragewidth,
      roomgamelength: resProperties.roomgamelength,
      roomgamewidth: resProperties.roomgamewidth,
      roomguestlength: resProperties.roomguestlength,
      roomguestwidth: resProperties.roomguestwidth,
      roomlibrarylength: resProperties.roomlibrarylength,
      roomlibrarywidth: resProperties.roomlibrarywidth,
      roommedialength: resProperties.roommedialength,
      roommediawidth: resProperties.roommediawidth,
      roommudlength: resProperties.roommudlength,
      roommudwidth: resProperties.roommudwidth,
      roomofficelength: resProperties.roomofficelength,
      roomofficewidth: resProperties.roomofficewidth,
      roomsaunalength: resProperties.roomsaunalength,
      roomsaunawidth: resProperties.roomsaunawidth,
      roomsecondmasterlength: resProperties.roomsecondmasterlength,
      roomsecondmasterwidth: resProperties.roomsecondmasterwidth,
      roomsunlength: resProperties.roomsunlength,
      roomsunwidth: resProperties.roomsunwidth,
      roomspalength: resProperties.roomspalength,
      roomspawidth: resProperties.roomspawidth,
      roomwinelength: resProperties.roomwinelength,
      roomwinewidth: resProperties.roomwinewidth,
      juniorhighschoolname: resProperties.juniorhighschoolname,
      primaryschoolname: resProperties.primaryschoolname,
      seniorhighschoolname: resProperties.seniorhighschoolname,
      associationfee: resProperties.associationfee,
      associationfeefrequency: resProperties.associationfeefrequency,
      constructionmaterials: resProperties.constructionmaterials,
      heating: resProperties.heating,
      accessoryunittype: resProperties.accessoryunittype,
      accessoryunityn: resProperties.accessoryunityn,
      flooring: resProperties.flooring,
      fireplacestotal: resProperties.fireplacestotal,
      fireplacefeatures: resProperties.fireplacefeatures,
      securitysystemyn: resProperties.securitysystemyn,
      greenbuildingcertification: resProperties.greenbuildingcertification,
      greenenergyefficient: resProperties.greenenergyefficient,
      energysavingfeatures: resProperties.energysavingfeatures,
      lotnumber: resProperties.lotnumber,
      lotsizearea: resProperties.lotsizearea,
      lotsizedimensions: resProperties.lotsizedimensions,
      easements: resProperties.easements,
      restrictions: resProperties.restrictions,
      washerdryerconnections: resProperties.washerdryerconnections,
      municipalutilitydistrictyn: resProperties.municipalutilitydistrictyn,
      associationfeeincludes: resProperties.associationfeeincludes,
      associationtype: resProperties.associationtype,
      barninformation: resProperties.barninformation,
      constructionmaterialswalls: resProperties.constructionmaterialswalls,
      countyorparish: resProperties.countyorparish,
      exteriorbuildings: resProperties.exteriorbuildings,
      farmranchfeatures: resProperties.farmranchfeatures,
      fencedyardyn: resProperties.fencedyardyn,
      financingproposed: resProperties.financingproposed,
      handicapyn: resProperties.handicapyn,
      numberoftanksandponds: resProperties.numberoftanksandponds,
      parcelnumber: resProperties.parcelnumber,
      virtualtoururlunbranded: resProperties.virtualtoururlunbranded,
      livingRoomFeature: resProperties.livingRoomFeature,
      masterBedRoomFeature: resProperties.masterBedRoomFeature,
      bedRoomFeature: resProperties.bedRoomFeature,
      diningRoomFeature: resProperties.diningRoomFeature,
      kitchenRoomFeature: resProperties.kitchenRoomFeature,
      breakfastRoomFeature: resProperties.breakfastRoomFeature,
      studyRoomFeature: resProperties.studyRoomFeature,
      utilityRoomFeature: resProperties.utilityRoomFeature,
      fullBathRoomFeature: resProperties.fullBathRoomFeature,
      halfBathRoomFeature: resProperties.halfBathRoomFeature,
      exerciseRoomFeature: resProperties.exerciseRoomFeature,
      extraStorageRoomFeature: resProperties.extraStorageRoomFeature,
      gameRoomFeature: resProperties.gameRoomFeature,
      guestRoomFeature: resProperties.guestRoomFeature,
      libraryRoomFeature: resProperties.libraryRoomFeature,
      mediaRoomFeature: resProperties.mediaRoomFeature,
      mudRoomFeature: resProperties.mudRoomFeature,
      officeRoomFeature: resProperties.officeRoomFeature,
      saunaRoomFeature: resProperties.saunaRoomFeature,
      secondMasterRoomFeature: resProperties.secondMasterRoomFeature,
      sunroomRoomFeature: resProperties.sunroomRoomFeature,
      spaRoomFeature: resProperties.spaRoomFeature,
      wineRoomFeature: resProperties.wineRoomFeature,
      otherRoomFeature: resProperties.otherRoomFeature,
      isLuxury: resProperties.isLuxury,
      isMoveInReady: resProperties.isMoveInReady,
      photoUrl: resProperties.photoUrl,
      photo1Url: resProperties.photo1Url,
      photo2Url: resProperties.photo2Url,
      photo3Url: resProperties.photo3Url,
      photo4Url: resProperties.photo4Url,
      photo5Url: resProperties.photo5Url,
      photo6Url: resProperties.photo6Url,
      photo7Url: resProperties.photo7Url,
      photo8Url: resProperties.photo8Url,
      photo9Url: resProperties.photo9Url,
      photo10Url: resProperties.photo10Url,
      photo11Url: resProperties.photo11Url,
      photo12Url: resProperties.photo12Url,
      photo13Url: resProperties.photo13Url,
      photo14Url: resProperties.photo14Url,
      photo15Url: resProperties.photo15Url,
      photo16Url: resProperties.photo16Url,
      photo17Url: resProperties.photo17Url,
      photo18Url: resProperties.photo18Url,
      photo19Url: resProperties.photo19Url,
      photo20Url: resProperties.photo20Url,
      photo21Url: resProperties.photo21Url,
      photo22Url: resProperties.photo22Url,
      photo23Url: resProperties.photo23Url,
      photo24Url: resProperties.photo24Url,
      photo25Url: resProperties.photo25Url,
      photo26Url: resProperties.photo26Url,
      photo27Url: resProperties.photo27Url,
      photo28Url: resProperties.photo28Url,
      photo29Url: resProperties.photo29Url,
      photo30Url: resProperties.photo30Url,
      photo31Url: resProperties.photo31Url,
      photo32Url: resProperties.photo32Url,
      photo33Url: resProperties.photo33Url,
      photo34Url: resProperties.photo34Url,
      photo35Url: resProperties.photo35Url,
      photo36Url: resProperties.photo36Url,
      photo37Url: resProperties.photo37Url,
      photo38Url: resProperties.photo38Url,
      photo39Url: resProperties.photo39Url,
      photo40Url: resProperties.photo40Url,
      created: resProperties.created ? resProperties.created.format(DATE_TIME_FORMAT) : null,
      updated: resProperties.updated ? resProperties.updated.format(DATE_TIME_FORMAT) : null,
      modifiedDate: resProperties.modifiedDate ? resProperties.modifiedDate.format(DATE_TIME_FORMAT) : null,
      imgDeleted: resProperties.imgDeleted,
      retsServer: resProperties.retsServer,
      permalink: resProperties.permalink,
      propertyTag: resProperties.propertyTag,
      buildentoryViews: resProperties.buildentoryViews,
      location: resProperties.location,
    });
  }

  protected createFromForm(): IResProperties {
    return {
      ...new ResProperties(),
      id: this.editForm.get(['id'])!.value,
      communityId: this.editForm.get(['communityId'])!.value,
      communityName: this.editForm.get(['communityName'])!.value,
      builderId: this.editForm.get(['builderId'])!.value,
      specialOffers: this.editForm.get(['specialOffers'])!.value,
      brochure: this.editForm.get(['brochure'])!.value,
      floorPlanId: this.editForm.get(['floorPlanId'])!.value,
      latitude: this.editForm.get(['latitude'])!.value,
      longitude: this.editForm.get(['longitude'])!.value,
      county: this.editForm.get(['county'])!.value,
      heatsystem: this.editForm.get(['heatsystem'])!.value,
      liststatus: this.editForm.get(['liststatus'])!.value,
      liststatusflag: this.editForm.get(['liststatusflag'])!.value,
      carportcap: this.editForm.get(['carportcap'])!.value,
      possession: this.editForm.get(['possession'])!.value,
      schoolname1: this.editForm.get(['schoolname1'])!.value,
      subdivide: this.editForm.get(['subdivide'])!.value,
      vowavmyn: this.editForm.get(['vowavmyn'])!.value,
      presentuse: this.editForm.get(['presentuse'])!.value,
      proposeduse: this.editForm.get(['proposeduse'])!.value,
      ranchname: this.editForm.get(['ranchname'])!.value,
      roombed2width: this.editForm.get(['roombed2width'])!.value,
      roomdininglevel: this.editForm.get(['roomdininglevel'])!.value,
      roomliving2width: this.editForm.get(['roomliving2width'])!.value,
      roomstudylevel: this.editForm.get(['roomstudylevel'])!.value,
      area: this.editForm.get(['area'])!.value,
      areatitle: this.editForm.get(['areatitle'])!.value,
      assocfee: this.editForm.get(['assocfee'])!.value,
      financeproposed: this.editForm.get(['financeproposed'])!.value,
      listpriceorig: this.editForm.get(['listpriceorig'])!.value,
      mapcoord: this.editForm.get(['mapcoord'])!.value,
      schoolname2: this.editForm.get(['schoolname2'])!.value,
      roomgaragewidth: this.editForm.get(['roomgaragewidth'])!.value,
      roomkitchendesc: this.editForm.get(['roomkitchendesc'])!.value,
      roomliving1width: this.editForm.get(['roomliving1width'])!.value,
      roomother2width: this.editForm.get(['roomother2width'])!.value,
      sqfttotal: this.editForm.get(['sqfttotal'])!.value,
      officelistOfficenam1: this.editForm.get(['officelistOfficenam1'])!.value,
      schoolname3: this.editForm.get(['schoolname3'])!.value,
      zipcode: this.editForm.get(['zipcode'])!.value,
      barn1length: this.editForm.get(['barn1length'])!.value,
      barn3width: this.editForm.get(['barn3width'])!.value,
      roombed2length: this.editForm.get(['roombed2length'])!.value,
      roombed3length: this.editForm.get(['roombed3length'])!.value,
      roomother1width: this.editForm.get(['roomother1width'])!.value,
      agentlistFullname: this.editForm.get(['agentlistFullname'])!.value,
      proptype: this.editForm.get(['proptype'])!.value,
      mlsProptype: this.editForm.get(['mlsProptype'])!.value,
      schoolname4: this.editForm.get(['schoolname4'])!.value,
      acrescultivated: this.editForm.get(['acrescultivated'])!.value,
      barn2length: this.editForm.get(['barn2length'])!.value,
      barn2width: this.editForm.get(['barn2width'])!.value,
      complexname: this.editForm.get(['complexname'])!.value,
      roombed4length: this.editForm.get(['roombed4length'])!.value,
      roombedbathdesc: this.editForm.get(['roombedbathdesc'])!.value,
      roombreakfastwidth: this.editForm.get(['roombreakfastwidth'])!.value,
      roomother: this.editForm.get(['roomother'])!.value,
      roomutilitylength: this.editForm.get(['roomutilitylength'])!.value,
      acres: this.editForm.get(['acres'])!.value,
      block: this.editForm.get(['block'])!.value,
      directions: this.editForm.get(['directions'])!.value,
      subdivision: this.editForm.get(['subdivision'])!.value,
      yearbuilt: this.editForm.get(['yearbuilt'])!.value,
      yearbuiltdetails: this.editForm.get(['yearbuiltdetails'])!.value,
      agexemption: this.editForm.get(['agexemption'])!.value,
      barn1width: this.editForm.get(['barn1width'])!.value,
      barn3length: this.editForm.get(['barn3length'])!.value,
      roomdiningwidth: this.editForm.get(['roomdiningwidth'])!.value,
      roomstudywidth: this.editForm.get(['roomstudywidth'])!.value,
      soiltype: this.editForm.get(['soiltype'])!.value,
      appraisername: this.editForm.get(['appraisername'])!.value,
      listpricelow: this.editForm.get(['listpricelow'])!.value,
      mappage: this.editForm.get(['mappage'])!.value,
      unitnumber: this.editForm.get(['unitnumber'])!.value,
      streetdir: this.editForm.get(['streetdir'])!.value,
      streettype: this.editForm.get(['streettype'])!.value,
      subarea: this.editForm.get(['subarea'])!.value,
      subareatitle: this.editForm.get(['subareatitle'])!.value,
      bathshalf: this.editForm.get(['bathshalf'])!.value,
      roomgaragelength: this.editForm.get(['roomgaragelength'])!.value,
      propsubtype: this.editForm.get(['propsubtype'])!.value,
      beds: this.editForm.get(['beds'])!.value,
      roommasterbedwidth: this.editForm.get(['roommasterbedwidth'])!.value,
      roomstudylength: this.editForm.get(['roomstudylength'])!.value,
      agentlist: this.editForm.get(['agentlist'])!.value,
      streetname: this.editForm.get(['streetname'])!.value,
      roombreakfastlength: this.editForm.get(['roombreakfastlength'])!.value,
      roomkitchenwidth: this.editForm.get(['roomkitchenwidth'])!.value,
      fence: this.editForm.get(['fence'])!.value,
      bathstotal: this.editForm.get(['bathstotal'])!.value,
      garagecap: this.editForm.get(['garagecap'])!.value,
      sqftprice: this.editForm.get(['sqftprice'])!.value,
      style: this.editForm.get(['style'])!.value,
      exterior: this.editForm.get(['exterior'])!.value,
      foundation: this.editForm.get(['foundation'])!.value,
      interior: this.editForm.get(['interior'])!.value,
      poolyn: this.editForm.get(['poolyn'])!.value,
      poolFeature: this.editForm.get(['poolFeature'])!.value,
      listprice: this.editForm.get(['listprice'])!.value,
      listpricerange: this.editForm.get(['listpricerange'])!.value,
      mlsnum: this.editForm.get(['mlsnum'])!.value,
      matrixid: this.editForm.get(['matrixid'])!.value,
      remarks: this.editForm.get(['remarks'])!.value,
      state: this.editForm.get(['state'])!.value,
      roof: this.editForm.get(['roof'])!.value,
      securityfeatures: this.editForm.get(['securityfeatures'])!.value,
      utilitiesother: this.editForm.get(['utilitiesother'])!.value,
      commonfeatures: this.editForm.get(['commonfeatures'])!.value,
      construction: this.editForm.get(['construction'])!.value,
      modified: this.editForm.get(['modified'])!.value ? dayjs(this.editForm.get(['modified'])!.value, DATE_TIME_FORMAT) : undefined,
      stories: this.editForm.get(['stories'])!.value,
      roomdininglength: this.editForm.get(['roomdininglength'])!.value,
      roomliving1length: this.editForm.get(['roomliving1length'])!.value,
      openhousetime: this.editForm.get(['openhousetime'])!.value,
      openhouseendtime: this.editForm.get(['openhouseendtime'])!.value,
      roomliving2length: this.editForm.get(['roomliving2length'])!.value,
      lotdesc: this.editForm.get(['lotdesc'])!.value,
      openhousedate: this.editForm.get(['openhousedate'])!.value
        ? dayjs(this.editForm.get(['openhousedate'])!.value, DATE_TIME_FORMAT)
        : undefined,
      roommasterbedlength: this.editForm.get(['roommasterbedlength'])!.value,
      roomother1length: this.editForm.get(['roomother1length'])!.value,
      officesellOfficenam2: this.editForm.get(['officesellOfficenam2'])!.value,
      lotsize: this.editForm.get(['lotsize'])!.value,
      streetdirsuffix: this.editForm.get(['streetdirsuffix'])!.value,
      photocount: this.editForm.get(['photocount'])!.value,
      schooldistrict: this.editForm.get(['schooldistrict'])!.value,
      streetnum: this.editForm.get(['streetnum'])!.value,
      utilities: this.editForm.get(['utilities'])!.value,
      equipment: this.editForm.get(['equipment'])!.value,
      roombed4width: this.editForm.get(['roombed4width'])!.value,
      roomkitchenlength: this.editForm.get(['roomkitchenlength'])!.value,
      city: this.editForm.get(['city'])!.value,
      garagedesc: this.editForm.get(['garagedesc'])!.value,
      bathsfull: this.editForm.get(['bathsfull'])!.value,
      roombed3width: this.editForm.get(['roombed3width'])!.value,
      roomutildesc: this.editForm.get(['roomutildesc'])!.value,
      roomutilitywidth: this.editForm.get(['roomutilitywidth'])!.value,
      roomfullbathlength: this.editForm.get(['roomfullbathlength'])!.value,
      roomfullbathwidth: this.editForm.get(['roomfullbathwidth'])!.value,
      roomhalfbathlength: this.editForm.get(['roomhalfbathlength'])!.value,
      roomhalfbathwidth: this.editForm.get(['roomhalfbathwidth'])!.value,
      roomexerciselength: this.editForm.get(['roomexerciselength'])!.value,
      roomexercisewidth: this.editForm.get(['roomexercisewidth'])!.value,
      roomstoragelength: this.editForm.get(['roomstoragelength'])!.value,
      roomstoragewidth: this.editForm.get(['roomstoragewidth'])!.value,
      roomgamelength: this.editForm.get(['roomgamelength'])!.value,
      roomgamewidth: this.editForm.get(['roomgamewidth'])!.value,
      roomguestlength: this.editForm.get(['roomguestlength'])!.value,
      roomguestwidth: this.editForm.get(['roomguestwidth'])!.value,
      roomlibrarylength: this.editForm.get(['roomlibrarylength'])!.value,
      roomlibrarywidth: this.editForm.get(['roomlibrarywidth'])!.value,
      roommedialength: this.editForm.get(['roommedialength'])!.value,
      roommediawidth: this.editForm.get(['roommediawidth'])!.value,
      roommudlength: this.editForm.get(['roommudlength'])!.value,
      roommudwidth: this.editForm.get(['roommudwidth'])!.value,
      roomofficelength: this.editForm.get(['roomofficelength'])!.value,
      roomofficewidth: this.editForm.get(['roomofficewidth'])!.value,
      roomsaunalength: this.editForm.get(['roomsaunalength'])!.value,
      roomsaunawidth: this.editForm.get(['roomsaunawidth'])!.value,
      roomsecondmasterlength: this.editForm.get(['roomsecondmasterlength'])!.value,
      roomsecondmasterwidth: this.editForm.get(['roomsecondmasterwidth'])!.value,
      roomsunlength: this.editForm.get(['roomsunlength'])!.value,
      roomsunwidth: this.editForm.get(['roomsunwidth'])!.value,
      roomspalength: this.editForm.get(['roomspalength'])!.value,
      roomspawidth: this.editForm.get(['roomspawidth'])!.value,
      roomwinelength: this.editForm.get(['roomwinelength'])!.value,
      roomwinewidth: this.editForm.get(['roomwinewidth'])!.value,
      juniorhighschoolname: this.editForm.get(['juniorhighschoolname'])!.value,
      primaryschoolname: this.editForm.get(['primaryschoolname'])!.value,
      seniorhighschoolname: this.editForm.get(['seniorhighschoolname'])!.value,
      associationfee: this.editForm.get(['associationfee'])!.value,
      associationfeefrequency: this.editForm.get(['associationfeefrequency'])!.value,
      constructionmaterials: this.editForm.get(['constructionmaterials'])!.value,
      heating: this.editForm.get(['heating'])!.value,
      accessoryunittype: this.editForm.get(['accessoryunittype'])!.value,
      accessoryunityn: this.editForm.get(['accessoryunityn'])!.value,
      flooring: this.editForm.get(['flooring'])!.value,
      fireplacestotal: this.editForm.get(['fireplacestotal'])!.value,
      fireplacefeatures: this.editForm.get(['fireplacefeatures'])!.value,
      securitysystemyn: this.editForm.get(['securitysystemyn'])!.value,
      greenbuildingcertification: this.editForm.get(['greenbuildingcertification'])!.value,
      greenenergyefficient: this.editForm.get(['greenenergyefficient'])!.value,
      energysavingfeatures: this.editForm.get(['energysavingfeatures'])!.value,
      lotnumber: this.editForm.get(['lotnumber'])!.value,
      lotsizearea: this.editForm.get(['lotsizearea'])!.value,
      lotsizedimensions: this.editForm.get(['lotsizedimensions'])!.value,
      easements: this.editForm.get(['easements'])!.value,
      restrictions: this.editForm.get(['restrictions'])!.value,
      washerdryerconnections: this.editForm.get(['washerdryerconnections'])!.value,
      municipalutilitydistrictyn: this.editForm.get(['municipalutilitydistrictyn'])!.value,
      associationfeeincludes: this.editForm.get(['associationfeeincludes'])!.value,
      associationtype: this.editForm.get(['associationtype'])!.value,
      barninformation: this.editForm.get(['barninformation'])!.value,
      constructionmaterialswalls: this.editForm.get(['constructionmaterialswalls'])!.value,
      countyorparish: this.editForm.get(['countyorparish'])!.value,
      exteriorbuildings: this.editForm.get(['exteriorbuildings'])!.value,
      farmranchfeatures: this.editForm.get(['farmranchfeatures'])!.value,
      fencedyardyn: this.editForm.get(['fencedyardyn'])!.value,
      financingproposed: this.editForm.get(['financingproposed'])!.value,
      handicapyn: this.editForm.get(['handicapyn'])!.value,
      numberoftanksandponds: this.editForm.get(['numberoftanksandponds'])!.value,
      parcelnumber: this.editForm.get(['parcelnumber'])!.value,
      virtualtoururlunbranded: this.editForm.get(['virtualtoururlunbranded'])!.value,
      livingRoomFeature: this.editForm.get(['livingRoomFeature'])!.value,
      masterBedRoomFeature: this.editForm.get(['masterBedRoomFeature'])!.value,
      bedRoomFeature: this.editForm.get(['bedRoomFeature'])!.value,
      diningRoomFeature: this.editForm.get(['diningRoomFeature'])!.value,
      kitchenRoomFeature: this.editForm.get(['kitchenRoomFeature'])!.value,
      breakfastRoomFeature: this.editForm.get(['breakfastRoomFeature'])!.value,
      studyRoomFeature: this.editForm.get(['studyRoomFeature'])!.value,
      utilityRoomFeature: this.editForm.get(['utilityRoomFeature'])!.value,
      fullBathRoomFeature: this.editForm.get(['fullBathRoomFeature'])!.value,
      halfBathRoomFeature: this.editForm.get(['halfBathRoomFeature'])!.value,
      exerciseRoomFeature: this.editForm.get(['exerciseRoomFeature'])!.value,
      extraStorageRoomFeature: this.editForm.get(['extraStorageRoomFeature'])!.value,
      gameRoomFeature: this.editForm.get(['gameRoomFeature'])!.value,
      guestRoomFeature: this.editForm.get(['guestRoomFeature'])!.value,
      libraryRoomFeature: this.editForm.get(['libraryRoomFeature'])!.value,
      mediaRoomFeature: this.editForm.get(['mediaRoomFeature'])!.value,
      mudRoomFeature: this.editForm.get(['mudRoomFeature'])!.value,
      officeRoomFeature: this.editForm.get(['officeRoomFeature'])!.value,
      saunaRoomFeature: this.editForm.get(['saunaRoomFeature'])!.value,
      secondMasterRoomFeature: this.editForm.get(['secondMasterRoomFeature'])!.value,
      sunroomRoomFeature: this.editForm.get(['sunroomRoomFeature'])!.value,
      spaRoomFeature: this.editForm.get(['spaRoomFeature'])!.value,
      wineRoomFeature: this.editForm.get(['wineRoomFeature'])!.value,
      otherRoomFeature: this.editForm.get(['otherRoomFeature'])!.value,
      isLuxury: this.editForm.get(['isLuxury'])!.value,
      isMoveInReady: this.editForm.get(['isMoveInReady'])!.value,
      photoUrl: this.editForm.get(['photoUrl'])!.value,
      photo1Url: this.editForm.get(['photo1Url'])!.value,
      photo2Url: this.editForm.get(['photo2Url'])!.value,
      photo3Url: this.editForm.get(['photo3Url'])!.value,
      photo4Url: this.editForm.get(['photo4Url'])!.value,
      photo5Url: this.editForm.get(['photo5Url'])!.value,
      photo6Url: this.editForm.get(['photo6Url'])!.value,
      photo7Url: this.editForm.get(['photo7Url'])!.value,
      photo8Url: this.editForm.get(['photo8Url'])!.value,
      photo9Url: this.editForm.get(['photo9Url'])!.value,
      photo10Url: this.editForm.get(['photo10Url'])!.value,
      photo11Url: this.editForm.get(['photo11Url'])!.value,
      photo12Url: this.editForm.get(['photo12Url'])!.value,
      photo13Url: this.editForm.get(['photo13Url'])!.value,
      photo14Url: this.editForm.get(['photo14Url'])!.value,
      photo15Url: this.editForm.get(['photo15Url'])!.value,
      photo16Url: this.editForm.get(['photo16Url'])!.value,
      photo17Url: this.editForm.get(['photo17Url'])!.value,
      photo18Url: this.editForm.get(['photo18Url'])!.value,
      photo19Url: this.editForm.get(['photo19Url'])!.value,
      photo20Url: this.editForm.get(['photo20Url'])!.value,
      photo21Url: this.editForm.get(['photo21Url'])!.value,
      photo22Url: this.editForm.get(['photo22Url'])!.value,
      photo23Url: this.editForm.get(['photo23Url'])!.value,
      photo24Url: this.editForm.get(['photo24Url'])!.value,
      photo25Url: this.editForm.get(['photo25Url'])!.value,
      photo26Url: this.editForm.get(['photo26Url'])!.value,
      photo27Url: this.editForm.get(['photo27Url'])!.value,
      photo28Url: this.editForm.get(['photo28Url'])!.value,
      photo29Url: this.editForm.get(['photo29Url'])!.value,
      photo30Url: this.editForm.get(['photo30Url'])!.value,
      photo31Url: this.editForm.get(['photo31Url'])!.value,
      photo32Url: this.editForm.get(['photo32Url'])!.value,
      photo33Url: this.editForm.get(['photo33Url'])!.value,
      photo34Url: this.editForm.get(['photo34Url'])!.value,
      photo35Url: this.editForm.get(['photo35Url'])!.value,
      photo36Url: this.editForm.get(['photo36Url'])!.value,
      photo37Url: this.editForm.get(['photo37Url'])!.value,
      photo38Url: this.editForm.get(['photo38Url'])!.value,
      photo39Url: this.editForm.get(['photo39Url'])!.value,
      photo40Url: this.editForm.get(['photo40Url'])!.value,
      created: this.editForm.get(['created'])!.value ? dayjs(this.editForm.get(['created'])!.value, DATE_TIME_FORMAT) : undefined,
      updated: this.editForm.get(['updated'])!.value ? dayjs(this.editForm.get(['updated'])!.value, DATE_TIME_FORMAT) : undefined,
      modifiedDate: this.editForm.get(['modifiedDate'])!.value
        ? dayjs(this.editForm.get(['modifiedDate'])!.value, DATE_TIME_FORMAT)
        : undefined,
      imgDeleted: this.editForm.get(['imgDeleted'])!.value,
      retsServer: this.editForm.get(['retsServer'])!.value,
      permalink: this.editForm.get(['permalink'])!.value,
      propertyTag: this.editForm.get(['propertyTag'])!.value,
      buildentoryViews: this.editForm.get(['buildentoryViews'])!.value,
      location: this.editForm.get(['location'])!.value,
    };
  }
}
